### ISSUE TITLE
Search & Notion links in the Navigation menu

### ISSUE THREAD

**Issue by dosoft** [leoncvlt/loconotion#11]
Seems like they just added these items (search & notion) links into the navigation menu (top row).
And these items render using desktop layout therefore cause issues on the mobile

**Comment by leoncvlt** [comment]
As far as I know, the search & notion menu in the top right have always been there - they should be removed with this css rule:
```css
.notion-topbar > div > div:not(:first-child) {
  display: none !important;
}
```
I tested a few sites and it seems to work correctly. What problems are you having with the specifically?
