### ISSUE TITLE
Docker build loconotion failed.

### ISSUE THREAD

**Issue by ngbao161199** [leoncvlt/loconotion#137]
Hi @leoncvlt 

I setup my yml like this

```
name: Publish Notion website to GitHub Pages

on:
  # Manual update only.
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
    deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout loconotion
          uses: actions/checkout@v3
          with:
            repository: leoncvlt/loconotion
            path: loconotion
        - name: Checkout this repo
          uses: actions/checkout@v3
          with:
            path: pages_repo
  
        - name: Build Loconotion docker image
          run: docker-compose build loconotion
          working-directory: loconotion
          
        - name: Run Loconotion
          run: |
            docker run \
            -v "$GITHUB_WORKSPACE/pages_repo/dist:/app/loconotion/dist" \
            -v "$GITHUB_WORKSPACE/pages_repo/site.toml:/app/loconotion/site.toml" \
            loconotion "site.toml"
          working-directory: loconotion
        - name: Push to GitHub pages
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            
            GIT_DEPLOY_DIR=dist/site \
            GIT_DEPLOY_BRANCH=gh-pages \
            GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git" ./deploy.sh
          working-directory: pages_repo
```

However, I got this error from `run: docker-compose build loconotion`. Do u know how to fix it?

```
ERROR: failed to solve: process "/bin/sh -c wget --no-verbose -O /tmp/chrome.deb [https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb](https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_$%7BCHROME_VERSION%7D_amd64.deb)   && apt install -y /tmp/chrome.deb   && rm /tmp/chrome.deb" did not complete successfully: exit code: 8
Service 'loconotion' failed to build : Build failed
Error: Process completed with exit code 1.
```

**Comment by Trost123** [comment]
Looks like this happens because the crome download link is broken (404):

https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_99.0.4844.74-1_amd64.deb

Maybe it's possible to bump the "chrome version" variable.

**Comment by Trost123** [comment]
As I understand this is the file where the no longer valid chrome version is set:

https://github.com/leoncvlt/loconotion/blob/eb86257da02c5f540a5336b4bc11b69a038c2633/docker/Dockerfile#L14

**Comment by ngbao161199** [comment]
> Looks like this happens because the crome download link is broken (404):
> 
> https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_99.0.4844.74-1_amd64.deb
> 
> Maybe it's possible to bump the "chrome version" variable.

Maybe we can use this alternative link? @Trost123 
http://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_99.0.4844.51-1_amd64.deb

**Comment by ngbao161199** [comment]
Btw @Trost123 , do u know how to fix it?

**Comment by Trost123** [comment]
> Btw @Trost123 , do u know how to fix it?

I'd probably fork this repo and fix the chrome url or version. But I don't know how to use the forked version in:
```
docker-compose build loconotion
```

And I don't have time right now to figure it out.
Hopefully the authors of this project can fix it soon.

**Comment by choux130** [comment]
I encountered the same issue and spent some time troubleshooting it. Here is the modified Dockerfile which works for me, [https://github.com/leoncvlt/loconotion/pull/138](https://github.com/leoncvlt/loconotion/pull/138). Before the author approves my PR, my workaround is to point to my repo, `choux130/loconotion`, instead of `leoncvlt/loconotion`.

This is my code snippet,
```
      - name: Checkout loconotion
        uses: actions/checkout@v2
        with:
          repository: choux130/loconotion
          path: loconotion
```
from [https://github.com/choux130/myblog-yintingchou-notion/blob/main/.github/workflows/pages_deploy.yml](https://github.com/choux130/myblog-yintingchou-notion/blob/main/.github/workflows/pages_deploy.yml)

Hope this help!
