### ISSUE TITLE
Rendering issues on Chromium on Linux

### ISSUE THREAD

**Issue by SYZYGY-DEV333** [leoncvlt/loconotion#31]
Hi, After looking through a couple of the other issues here, it seems that rendering issues have been brought up before, so I expect that you might ask me to continue this thread under issue #1 .

However, I thought I might provide a bit more detail about what I'm seeing right now, just to see if there were any more specific fixes.

## Glitch 1:
![glitch1](https://user-images.githubusercontent.com/10455379/105730541-7b663f00-5efc-11eb-9ea7-a4379312cca0.png)
As you can see here, the properties for this list view are distorted. That's an issue that I think was brought up previously, but I wanted to add my example here.

## Glitch 2:
![glitch2](https://user-images.githubusercontent.com/10455379/105730686-a18bdf00-5efc-11eb-9d3f-223a2dfeb845.png)
The titles of each columns on this table view are missing.

## Glitch 3:
![Screenshot from 2021-01-25 10-56-11](https://user-images.githubusercontent.com/10455379/105730774-b6687280-5efc-11eb-961c-6b122594770c.png)
The preview on this gallery view is not visible.

For reference, [here is the site generated by loconotion](https://syzygy-dev333.github.io/personal-website/joshua-sobel.html) and [here is what it's supposed to look like.](https://www.notion.so/sobelj/Joshua-Sobel-64e7f9095d7245c6987ec6687fcf4c39)

Here is my config file.
```toml
## Loconotion Site Configuration File ##
# This Config is for my notion-powered personal site

# name of the folder that the site will be generated in
name = "personal-website"

# the notion.so page to being parsing from. This page will become the index.html
# of the generated site, and loconotion will parse all sub-pages present on the page
page = "https://www.notion.so/sobelj/Joshua-Sobel-64e7f9095d7245c6987ec6687fcf4c39"

# optionally apply notion's dark mode, remove the line below to use the default light mode
theme = "dark"
```
Any help would be much appreciated.
